#!/bin/bash
clear
# Màu sắc cho console
PINK='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Banner
echo -e "${GREEN}"
echo "Cre: KASIO 2K9"
echo "Chào mừng!"
echo -e "${NC}"

# Hiển thị danh sách file
echo -e "${GREEN}folder 880btg_ropchain:${NC}"
echo "----------------------------------------"
files=(./880btg_ropchain/*)
count=1
for file in "${files[@]}"; do
    filename=$(basename "$file")
    echo -e "${GREEN}$count)${NC} $filename"
    ((count++))
done
echo "----------------------------------------"

# Nhập tên file
echo -e "${GREEN}Enter the file name: ${NC}"
read name

# Kiểm tra file tồn tại
if [ -f "./880btg_ropchain/$name" ]; then
    echo -e "${GREEN}Processing the $name...${NC}"
    python ./880btg/compiler_.py -f hex < "./880btg_ropchain/$name"
else
    echo -e "${GREEM}fuck you have error: File $name not found!${NC}"
fi
